### PR TITLE
Add Jansson type with dump() and dumps()

### PR DESCRIPTION
**Pull request by tiran**
```
>>> import pyjose
>>> jwk = pyjose.demo()
>>> jwk
<pyjose.Jansson object at 0x7f64935a80b0>
>>> jwk.dump()
{u'alg': u'A128GCM', u'use': u'enc', u'key_ops': [u'encrypt',
u'decrypt'], u'kty': u'oct', u'k': u'hiT7wXvtoWyMwd46zW1tQA'}
>>> jwk.dump()['alg']
u'A128GCM'
```

Signed-off-by: Christian Heimes cheimes@redhat.com

### CODE REVIEW

**Comment by npmccallum** [comment]
I'm sorry you spent a lot of work on this. I absolutely do not want to expose the jansson type.

**Comment by npmccallum** [comment]
pyjose will only ever accept/return dicts and strings. This is the strength of the pyjose API.

**Comment by tiran** [comment]
We aren't going to use the json module either. It's just a bad idea to pull another JSON library into this library. We have jansson and it works perfectly fine and fast.

We don't have to expose the jansson but we should use it internally.

**Comment by npmccallum** [comment]
Not mixing json implementations isn't a requirement. Here are our requirements:
1. Convert a dict/string to/from a json_t type internally.
2. Generate an exception when the input can't be converted to valid JSON.
3. The exceptions should be the same as what the Python standard json module throws.
4. Performance.
5. Don't add dependencies beyond Python stdlib.

Using my method of marshalling to JSON using the built-in json module solves all requirements except possibly 4 in a single line of code. It is thus far more maintainable. Now, your method might be required in the future to satisfy 4. But this will require great care in order to satisfy 3. It is also fragile and will be prone to breakage.

Hence, I'm strongly against this method until 4 can be shown to be a concern. Doing it before then is unnecessary optimization at great cost.

**Comment by npmccallum** [comment]
As I said on IRC, I think that this patch is roughly the size of the complete code base using my method. That means we double the size of the code base.

**Pull request closed without merging**
